[project]
name = "benchmark-charts"
version = "0.1.0"
description = "A command-line tool for visualizing Google Benchmark results as interactive HTML charts."
readme = "README.md"
authors = [
    { name = "jzcurious", email = "paranoid.hpc.io@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
    "plotly>=7.1.0",
]

[project.scripts]
benchmark-charts = "benchmark_charts.__main__:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
